### PR TITLE
#163289523 finish feedback 

### PR DESCRIPTION
**Pull request by JosephNjuguna**
### What does this PR do?
implements updated feedback from LFA
### Description of task to be completed
add descriptive message on run.py  link
add descriptive messages to inform user of an error or requirements
adds badges to readme file
### how should this be tested 
clone the repo : to your local machine.
open with terminal cd/Questioner
run the following command in your terminal
python -m pytest
open this link in your browser or postman:
```http://127.0.0.1:5000/```
### Relevant PT STORIES?
https://www.pivotaltracker.com/n/projects/2235137 > #163289523

### CODE REVIEW

**Comment by wangonya** [comment]
Good validations. Using too many return statements is not advisable though (according to pep8). Lookup how to use `raise` for validations 👍🏾

**Comment by JosephNjuguna** [comment]
noted that. i will  check on how to use `raise`

**Comment by betsybeth** [comment]
Merge and make sure to use PEP8 on challenge 3. It helps you with code syntax and maintainability of your code.

**Comment by JosephNjuguna** [comment]
okay. @betsybeth  I will make maximum use of PEP8 in challenge 3.

**Pull request merged**
