### PR TITLE
#163193632 added messages to inform user about api endpoints available

### PR DESCRIPTION
**Pull request by JosephNjuguna**
### What does this PR do?
this pr adds directive  message for my api endpoints
### Description of Task to be completed?
enable a user to know all available api endpoints for Questioner
### How should this be manually tested?

- clone this repo to your local machine
- open the project with terminal 
- run the following command on your  open terminal `python3 run.py`
- using postman , open link below 
`[GET] http://127.0.0.1:5000/`
screenshot from 2019-01-14 20-39-26

### What are the relevant pivotal tracker stories?
`https://www.pivotaltracker.com/n/projects/2235137`  _ #163193632 **fix run.py file**_

### CODE REVIEW

**Comment by betsybeth** [comment]
There is decrease in your coverage. Kindly work on this.

**Comment by JosephNjuguna** [comment]
thanks for the feedback I will check on my coverage.

**Comment by betsybeth** [comment]
The test coverage is reducing why?

**Comment by betsybeth** [comment]
You have conflicting files. Solve this

**Comment by JosephNjuguna** [comment]
yes. I am starting on refactoring my code increase my coverage

**Pull request merged**
